# Basic
title: Iyang ' Blog  
subtitle: eat！！！ sleep！！！ code！！！
welcome_message:  欢迎来到iyang的博客，本站在github Pages上搭建。
description: blog、code
creator: <a href="http://iyang.cc">@iyang</a>

url: "http://iyang.cc"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://www.iyang.cc'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 3204888104
    github: Miracle0528
    mail: 739827282@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
